# Nixpacks configuration for Railway
[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = [
  "npm ci --omit=dev --no-audit --no-fund"
]

[phases.build]
cmds = ["echo 'Build complete'"]

[phases.start]
cmd = "NODE_ENV=production node server.js"

[variables]
NODE_ENV = "production"
NPM_CONFIG_FUND = "false"
NPM_CONFIG_AUDIT = "false"